# Generated by Django 3.0 on 2024-09-23 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('is_subscribed', models.BooleanField(default=True, help_text='Is the user subscribed to receive alerts?')),
                ('subscription_area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('predicted_at', models.DateTimeField(help_text='Time when the prediction was made.')),
                ('temperature_high', models.FloatField(help_text='Predicted high temperature.')),
                ('temperature_low', models.FloatField(help_text='Predicted low temperature.')),
                ('wind_speed', models.FloatField(help_text='Predicted wind speed in m/s.')),
                ('chance_of_precipitation', models.FloatField(help_text='Chance of precipitation in percentage.')),
                ('forecast_date', models.DateField(help_text='The date for which this prediction is made.')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('reported_at', models.DateTimeField(help_text='Time when the report was logged.')),
                ('temperature', models.FloatField(help_text='Actual temperature.')),
                ('wind_speed', models.FloatField(help_text='Actual wind speed in m/s.')),
                ('precipitation', models.FloatField(help_text='Amount of precipitation in mm.')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('storm', 'Storm'), ('flood', 'Flood'), ('heatwave', 'Heatwave'), ('rain', 'Rain'), ('normal', 'Normal')], max_length=50)),
                ('description', models.TextField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='Time when this alert is no longer valid.')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile')),
            ],
        ),
    ]
