# Generated by Django 3.0 on 2024-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedweatheralert',
            name='location',
            field=models.CharField(default='location', max_length=255),
            preserve_default=False,
        ),
    ]
