# Generated by Django 3.0 on 2024-11-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_processedweatheralert_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
